language: node_js
node_js:
  - 'lts/*'

install:
  - npm install
  # - npm test
  - CI="false" npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: enigmator-web-app
    skip_cleanup: true
    on:
      branch: develop
      branch: master
    bucket: enigmator-storage
    region: eu-west-3

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: enigmator-storage
    key: latest-client.zip
    bundle_type: zip
    application: enigmator
    deployment_group: DeployEnigmator
    region: eu-west-3
    on:
      branch: develop
      branch: master

script:
  - zip -r latest-client build/ scripts/ appspec.yml Dockerfile .dockerignore
  - mkdir -p enigmator-web-app
  - mv latest-client.zip enigmator-web-app/latest-client.zip

notifications:
  email:
    recipients:
      - loic.colat@gmail.com
    on_success: never
    on_failure: always
