version: 0.0

os: linux

files:
  - source: ./
    destination: /home/ubuntu/enigmator/enigmator-web-app
hooks:
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 300
      runas: root 
