version: 0.0

os: linux

files:
  - source: ./
    destination: /home/ubuntu/enigmator/enigmator-web-app
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 300
      runas: ubuntu 
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 300
      runas: ubuntu 
